SET PATH=D:\Program Files\Keil5\ARM\ARMCC\bin\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Program Files\Java\jdk1.8.0_65\bin;D:\Program Files\Java\jdk1.8.0_65\jre\bin;D:\Program Files\apache-tomcat-8.0.32-windows-x64\apache-tomcat-8.0.32\lib;D:\Program Files\apache-tomcat-8.0.32-windows-x64\apache-tomcat-8.0.32\bin;D:\Program Files\mysql-5.7.11-winx64\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;D:\Program Files\sqlite-tools-win32-x86-3110000;D:\Program Files\Git\cmd
SET CPU_TYPE=STM32F407ZG
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=Target 1
SET CPU_CLOCK=0x017D7840
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\main.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\systeminit.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\stm32f4xx_it.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\led_driver.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\spi1_driver.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\spi2_driver.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\usart1_driver.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\usart2_driver.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\usart3_driver.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\usart4_driver.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\usart6_driver.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\tlv5617_driver.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\drv8825_driver.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\ads8325_driver.__i"
"D:\Program Files\Keil5\ARM\ARMCC\bin\ArmCC" --Via ".\obj\codescanner_driver.__i"
